# Generated by Django 6.0.2 on 2026-03-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название темы')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('category', models.CharField(choices=[('guitar', 'Гитара'), ('vocals', 'Вокал'), ('production', 'Продакшн'), ('drums', 'Ударные')], default='guitar', max_length=20, verbose_name='Категория')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'В архиве')], default='published', max_length=20, verbose_name='Статус')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'обсуждение',
                'verbose_name_plural': 'обсуждения',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
