# Generated by Django 6.0.2 on 2026-03-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicforum', '0002_seed_discussions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='Слаг'),
        ),
    ]
