# Generated by Django 5.2.12 on 2026-04-03 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicforum', '0003_alter_discussion_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Автор комментария')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='musicforum.discussion', verbose_name='Обсуждение')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DiscussionPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('bookmarks_count', models.PositiveIntegerField(default=0, verbose_name='Количество закладок')),
                ('discussion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='musicforum.discussion', verbose_name='Обсуждение')),
            ],
            options={
                'verbose_name': 'паспорт обсуждения',
                'verbose_name_plural': 'паспорта обсуждений',
            },
        ),
        migrations.AddField(
            model_name='discussion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='discussions', to='musicforum.tag', verbose_name='Теги'),
        ),
    ]
