# Generated by Django 5.2.12 on 2026-04-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicforum', '0005_seed_related_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
