# Generated by Django 5.2.14 on 2026-06-03 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicforum', '0006_discussion_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_comments', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discussions', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.CreateModel(
            name='DiscussionReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('like', 'Лайк'), ('dislike', 'Дизлайк')], max_length=10, verbose_name='Реакция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='musicforum.discussion', verbose_name='Обсуждение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'реакция на обсуждение',
                'verbose_name_plural': 'реакции на обсуждения',
                'constraints': [models.UniqueConstraint(fields=('discussion', 'user'), name='unique_discussion_reaction_per_user')],
            },
        ),
    ]
