# Generated by Django 5.2.14 on 2026-05-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('social_auth', 'Can manage social auth status')]},
        ),
        migrations.AddField(
            model_name='user',
            name='social_auth_verified',
            field=models.BooleanField(default=False, verbose_name='Социальная авторизация подтверждена'),
        ),
    ]
